#!/bin/csh

set SWIFT_DIR=
set FORTRAN=gfortran
# set FFLAGS='-auto -O3 -xW -c'
set FFLAGS='-O3 -c'
set PRECOMP=/usr/bin/cpp
set CPPFLAGS='-D_OPEN_POSITION -D_RECUR_SUB'

# To Profile the code:
#set FFLAGS='-G -c'

if (`ls *.F | wc -l` != 0 ) then
    echo Doing precompiler
    foreach file (*.F)
        echo $file | set file2=`awk -F"." '{print$1}'`
        echo $PRECOMP $CPPFLAGS "$file2".F "$file2"_CPP.f
        $PRECOMP $CPPFLAGS "$file2".F "$file2"_CPP.f
     end
else
    echo No need to precompile
endif

echo Doing Fortran
foreach file (*.f)
    echo $file | set file2=`awk -F"." '{print$1}'`
    echo $file2
    $FORTRAN $FFLAGS "$file2".f
    ar vr $SWIFT_DIR/libswift.a  "$file2".o
end

rm *.o
rm *CPP.f
echo Done directory $PWD

